{{- if .Values.appsmith_internal_server.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: appsmith-internal-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- with.Values.appsmith_internal_server.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appsmith_internal_server.name }}
  minReplicas: {{ .Values.appsmith_internal_server.hpa.minReplicas }}
  maxReplicas: {{ .Values.appsmith_internal_server.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.appsmith_internal_server.hpa.targetCPUUtilizationPercentage }}
{{- end }}
