apiVersion: v1
kind: Service
metadata:
  labels:
    {{- with.Values.appsmith_internal_server.podLabels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
  name: appsmith-backend-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.appsmith_internal_server.service.port }}
    protocol: TCP
    targetPort: {{ .Values.appsmith_internal_server.service.port }}
  selector:
    {{- with.Values.appsmith_internal_server.podLabels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
  sessionAffinity: None
  type: {{ .Values.appsmith_internal_server.service.type }}