apiVersion: v1
{{- with .Values.appsmith_editor.application_config.data }}
data:
{{- toYaml . | nindent 2 }}
{{- end }}
kind: ConfigMap
metadata:
  name: application-config
  namespace: {{ .Values.namespace }}