# To create a valid base64 encoded string use :
# kubectl create secret generic service-account-key --from-file=./sa.json -n gcpdev  --dry-run=client --output=yaml

{{- $secret := .Values.secret }}
{{- if $secret.enabled }}
apiVersion: v1
{{- with .Values.secret.data }}
data:
{{- toYaml . | nindent 2 }}
{{- end }}
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with.Values.appsmith_editor.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

